services:
    nginx:
        image: nginx:stable
        volumes:
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www
        ports:
            - '${APP_PORT:-8080}:80'
        restart: always
        depends_on:
            app:
                condition: service_started
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - '${VITE_PORT:-5173}:5173'
        restart: always
        depends_on:
            db:
                condition: service_healthy
        environment:
            PHP_IDE_CONFIG: "serverName=MyStore"
            XDEBUG_CONFIG: "idekey=PHPSTORM"
        container_name: app

    db:
        image: postgres
        restart: always
        shm_size: 128mb
        volumes:
            - db-volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DB_PORT:-5432}:5432'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        container_name: db

    redis:
        image: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        container_name: redis

volumes:
    db-volume:
        driver: local
        name: "MyStore-pgsql"
