services:
  nginx:
    image: nginx:stable
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www
    ports:
      - '${APP_PORT:-80}:80'
    restart: always
    depends_on:
      - app
    container_name: mystore_nginx

  app:
    image: ${APP_IMAGE}
    volumes:
      - ./:/var/www
    environment:
      - DB_PASSWORD=$${DB_PASSWORD}
    ports:
      - '${VITE_PORT:-5173}:5173'
    depends_on:
      - db
    container_name: mystore_app

  db:
    image: postgres
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=$${DB_PASSWORD}
    ports:
      - '${DB_PORT:-5432}:5432'
    container_name: mystore_db

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    container_name: mystore_redis

volumes:
  db-volume:
    driver: local
    name: "mystore_pgsql"
