services:
    nginx:
        image: nginx:stable
        volumes:
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www
        ports:
            - '${APP_PORT:-8080}:80'
        restart: always
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - '${VITE_PORT:-5173}:5173'
        depends_on:
            - db
        environment:
            PHP_IDE_CONFIG: "serverName=my-store"
        container_name: app

    db:
        image: postgres
        restart: always
        shm_size: 128mb
        volumes:
            - db-volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '${DB_PORT:-5432}:5432'
        container_name: db

    redis:
        image: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        container_name: redis

volumes:
    db-volume:
        driver: local
        name: "my-store-pgsql"
